name: Fetch upstream

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get manifests
        run: |
          git clone https://github.com/CrunchyData/postgres-operator-examples
          mkdir -p kustomize
          mkdir -p helm
          cp -rf postgres-operator-examples/kustomize/install kustomize
          cp -rf postgres-operator-examples/helm/install helm
          rm -rf postgres-operator-examples
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          title: "[bot] Automated update"
          signoff: false
          committer: Github <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            This is an automated update to manifest files from CI.

            Configuration of the workflow is located in `.github/workflows/fetch-upstream.yaml`
          labels: bot/update
